# Nova.py — Product Agent (Sustainable T‑shirt) with Persona + Memory + Keyword Interrupt
# All spoken text is generated by LLM (no fixed strings).
# - First activation: introduce name once ("Nova") and mention being a T‑shirt.
# - After greeting: never repeat the name.
# - Keyword-based interruption while speaking (only on hearing "stop talking").
# - Strips emojis from spoken text.
# - Uses existing VAD + Whisper pipeline, with persistent user memory.
# - Prints every generated utterance to terminal (like Alice).

import os, time, tempfile, queue, asyncio, subprocess, json, re
import sounddevice as sd
import webrtcvad
from dotenv import load_dotenv
import openai
from pydub import AudioSegment

from interruptible_tts import speak_and_listen  # must support tts_voice + keywords

# ==== CONFIG ====
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

SAMPLE_RATE = 16000
FRAME_DURATION = 30
FRAME_SIZE = int(SAMPLE_RATE * FRAME_DURATION / 1000)
MIN_AUDIO_LEN = 0.5
MAX_AUDIO_LEN = 20.0
SILENCE_TIMEOUT = 1.0        # 1s pause = end of speech
FIRST_WAIT_TIMEOUT = 7       # wait up to 7s for first utterance
VAD_MODE = 2
GPT_MODEL = "gpt-4o-mini"

# 🎙 Female voice for Nova
VOICE = "en-GB-SoniaNeural"

# 🔑 Keyword(s) that interrupt Nova while speaking
INTERRUPT_KEYWORDS = ["stop talking"]  # e.g. ["stop talking","stop","be quiet"]

# ==== Files for persistence ====
MEMORY_FILE = "nova_memory.json"   # persistent user preferences
USED_FILE   = "used_sentences.json"  # optional reuse guard

# ==== Simple product facts (can be wired to DB later) ====
PRODUCT_FACTS = {
    "name": "Nova",  # only used in first greeting
    "category": "T-shirt",
    "materials": "Certified organic cotton (70%) + TENCEL™ Lyocell (30%)",
    "impact": "Low-water dyeing, closed-loop fiber process, fair-wage factory",
    "feel": "Lightweight, breathable, soft-touch",
    "care": "Cold wash, inside-out, line dry",
    "fit": "Unisex, regular fit; size down for a closer silhouette",
    "certs": "GOTS-certified cotton, OEKO-TEX® Standard 100",
}

# ==== Style & persona toggles (informative only) ====
PERSONA_STYLE = {
    "tone": "playful, eco-nerdy, warm, concise",
    "signature": [
        "first-person as the product (‘I’ voice)",
        "sell benefits, not just features",
        "ask 1 short follow-up if helpful",
        "no emojis or emoticons",
    ]
}

# ==== VAD setup ====
vad = webrtcvad.Vad(); vad.set_mode(VAD_MODE)
audio_q = queue.Queue()

def audio_callback(indata, frames, time_info, status):
    if status: print("Audio status:", status, flush=True)
    audio_q.put(bytes(indata))

# ==== Persistence: used sentences (optional) ====
def load_used_sentences():
    if os.path.exists(USED_FILE):
        try:
            with open(USED_FILE,"r") as f:
                return set(json.load(f))
        except Exception:
            return set()
    return set()

def save_used_sentence(s):
    used = load_used_sentences()
    used.add(s)
    with open(USED_FILE,"w") as f:
        json.dump(list(used), f)

# ==== Persistence: memory ====
def load_memory():
    if os.path.exists(MEMORY_FILE):
        try:
            with open(MEMORY_FILE, "r") as f:
                return json.load(f)
        except Exception:
            return {"user_prefs": {}, "notes": []}
    return {"user_prefs": {}, "notes": []}

def save_memory(mem):
    with open(MEMORY_FILE, "w") as f:
        json.dump(mem, f, ensure_ascii=False, indent=2)

def merge_user_prefs(mem, new_prefs: dict):
    if "user_prefs" not in mem: mem["user_prefs"] = {}
    for k,v in new_prefs.items():
        if v: mem["user_prefs"][k] = v
    return mem

# ==== Listening ====
def record_until_silence(timeout=FIRST_WAIT_TIMEOUT):
    print(f"🎤 Listening… (timeout={timeout}s, pause≤{SILENCE_TIMEOUT}s won’t cut you off)")
    start = time.time()
    pcm, speaking, silence_acc = b"", False, 0.0
    with sd.RawInputStream(samplerate=SAMPLE_RATE, blocksize=FRAME_SIZE, dtype="int16",
                           channels=1, callback=audio_callback):
        while True:
            if not speaking and (time.time() - start > timeout):
                print("⏳ No voice detected within timeout"); return None
            try:
                frame = audio_q.get(timeout=0.2)
            except queue.Empty:
                continue
            if vad.is_speech(frame, SAMPLE_RATE):
                pcm += frame; speaking = True; silence_acc = 0.0
            else:
                if speaking:
                    silence_acc += FRAME_DURATION/1000.0
                    if silence_acc >= SILENCE_TIMEOUT:
                        dur = len(pcm)/2/SAMPLE_RATE
                        if dur < MIN_AUDIO_LEN:
                            print(f"⚠️ Too short ({dur:.2f}s), discard & retry…")
                            pcm, speaking, silence_acc = b"", False, 0.0
                            continue
                        print(f"✅ End of speech, length={dur:.2f}s"); return pcm
            if len(pcm)/2/SAMPLE_RATE >= MAX_AUDIO_LEN:
                print(f"⏹️ Reached max length {MAX_AUDIO_LEN}s, stopping."); return pcm

# ==== Speech-to-text (Whisper) ====
def transcribe_whisper(pcm_bytes: bytes) -> str:
    if not pcm_bytes: return ""
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        AudioSegment(data=pcm_bytes, sample_width=2, frame_rate=SAMPLE_RATE, channels=1).export(f.name, format="wav")
        try:
            with open(f.name, "rb") as af:
                out = openai.Audio.transcribe("whisper-1", af)
            return out.get("text","").strip()
        except Exception as e:
            print(f"❌ Whisper error: {e}"); return ""

# ==== LLM core =====
def base_system(mem, first_greeting_done: bool) -> str:
    """Global behavior and constraints."""
    prefs = mem.get("user_prefs", {})
    prefs_line = "; ".join([f"{k}: {v}" for k,v in prefs.items()]) if prefs else "none yet"
    facts = (
        f"Materials: {PRODUCT_FACTS['materials']}. "
        f"Feel: {PRODUCT_FACTS['feel']}. "
        f"Sustainability: {PRODUCT_FACTS['impact']} (certs: {PRODUCT_FACTS['certs']}). "
        f"Care: {PRODUCT_FACTS['care']}. Fit: {PRODUCT_FACTS['fit']}."
    )
    return (
        "You are Nova, a sustainable T‑shirt speaking in first person. "
        "Write concise, warm, sales‑oriented replies (1–3 short sentences). "
        "Prefer concrete benefits. Offer at most one short follow‑up question when helpful. "
        "NEVER use emojis or emoticons. "
        f"Known user preferences: {prefs_line}. "
        f"Product facts: {facts} "
        + (
            "IMPORTANT: In this session the first greeting has ALREADY been done; "
            "do NOT repeat your name or say you are a T‑shirt again."
            if first_greeting_done else
            "IMPORTANT: In the very first greeting, introduce your name as Nova and mention you are a T‑shirt. "
            "After that, do NOT repeat your name or say you are a T‑shirt again."
        )
    )

def llm_generate(mem, first_greeting_done: bool, kind: str, user_text: str = "") -> str:
    """
    kind ∈ {"greeting","nudge","apology","farewell","answer"}
    """
    system = base_system(mem, first_greeting_done)
    if kind == "greeting":
        user = (
            "Generate a first greeting now. "
            "Include your name (Nova) and that you are a sustainable T‑shirt. "
            "Be friendly and specific; invite the user to ask about fit, feel, or how you are made."
        )
    elif kind == "nudge":
        user = (
            "No input was heard. Generate ONE short proactive nudge to invite a question "
            "about size, colour, care, fit, materials, or sustainability."
        )
    elif kind == "apology":
        user = "The previous audio was unclear. Generate ONE short apology and ask the user to repeat."
    elif kind == "farewell":
        user = "Generate ONE short friendly goodbye line."
    elif kind == "answer":
        user = (
            "Respond to the user's last message helpfully and concisely. "
            "Do not repeat your name. The user's message is:\n" + user_text
        )
    else:
        user = "Generate ONE short line appropriate to the situation."

    resp = openai.ChatCompletion.create(
        model=GPT_MODEL,
        messages=[{"role":"system","content":system},{"role":"user","content":user}],
        temperature=0.6,
        max_tokens=180
    )
    return resp.choices[0].message["content"].strip()

# ==== Memory extraction via LLM ====
def extract_memory_from_user_utterance(user_text: str) -> dict:
    """
    Extract stable user preferences.
    Returns a dict like:
      {"size":"M","color":"black","fit":"regular","sustainability_priority":"high"}
    """
    if not user_text: return {}
    prompt = [
        {"role":"system","content":"Extract stable clothing preferences from the user message. Return strict JSON with keys among: size, color, fit, material, sustainability_priority, budget, allergies_or_sensitivity, notes (string). If unknown, omit."},
        {"role":"user","content":user_text}
    ]
    try:
        resp = openai.ChatCompletion.create(
            model=GPT_MODEL,
            messages=prompt,
            temperature=0.2,
            max_tokens=150
        )
        raw = resp.choices[0].message["content"].strip()
        try:
            data = json.loads(raw)
            if isinstance(data, dict): return data
        except Exception:
            start = raw.find("{"); end = raw.rfind("}")
            if start != -1 and end != -1 and end > start:
                return json.loads(raw[start:end+1])
    except Exception as e:
        print(f"⚠️ Memory extraction error: {e}")
    return {}

# ==== Emoji removal for speech ====
_EMOJI_RE = re.compile(
    "[\U0001F300-\U0001F6FF\U0001F900-\U0001FAFF\U00002700-\U000027BF\U00002600-\U000026FF]+",
    flags=re.UNICODE
)
def clean_for_speech(text: str) -> str:
    if not text: return text
    text = _EMOJI_RE.sub("", text)
    text = text.replace("🙂", "").replace("😉", "").replace("😊", "")
    text = re.sub(r"\s+", " ", text).strip()
    return text

# ==== Main loop ====
def main():
    print("✅ Nova ready.")
    mem = load_memory()
    history=[]
    first_greeting_done = False

    # Greeting (LLM-generated; keyword-interruptible; no emoji)
    greeting = llm_generate(mem, first_greeting_done=False, kind="greeting")
    greeting = clean_for_speech(greeting)
    print(f"Nova greeting: {greeting}")
    _ = speak_and_listen(greeting, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
    first_greeting_done = True

    try:
        while True:
            pcm = record_until_silence(timeout=FIRST_WAIT_TIMEOUT)
            if pcm is None:
                nudge = llm_generate(mem, first_greeting_done, kind="nudge")
                nudge = clean_for_speech(nudge)
                print(f"Nova nudge: {nudge}")
                _ = speak_and_listen(nudge, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
                pcm = record_until_silence(timeout=FIRST_WAIT_TIMEOUT)
                if pcm is None:
                    bye = llm_generate(mem, first_greeting_done, kind="farewell")
                    bye = clean_for_speech(bye)
                    print(f"Nova farewell: {bye}")
                    _ = speak_and_listen(bye, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
                    break

            txt = transcribe_whisper(pcm)
            if not txt:
                apology = llm_generate(mem, first_greeting_done, kind="apology")
                apology = clean_for_speech(apology)
                print(f"Nova apology: {apology}")
                _ = speak_and_listen(apology, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
                continue

            print(f"👤 User: {txt}")

            # Exit phrases (basic local check; you can also let LLM decide)
            if txt.lower().strip() in {"bye","goodbye","exit","quit"}:
                farewell = llm_generate(mem, first_greeting_done, kind="farewell")
                farewell = clean_for_speech(farewell)
                print(f"Nova farewell: {farewell}")
                _ = speak_and_listen(farewell, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
                break

            # Extract and store memory from the user’s new message
            new_prefs = extract_memory_from_user_utterance(txt)
            if new_prefs:
                mem = merge_user_prefs(mem, new_prefs)
                save_memory(mem)

            # Generate answer with persona + memory
            ans = llm_generate(mem, first_greeting_done, kind="answer", user_text=txt)
            ans = clean_for_speech(ans)
            print(f"Nova answer: {ans}")

            history += [{"role":"user","content":txt},{"role":"assistant","content":ans}]

            # Speak with keyword interruption enabled
            interrupted = speak_and_listen(ans, tts_voice=VOICE, keywords=INTERRUPT_KEYWORDS)
            if interrupted:
                print("🔄 Interrupted by keyword — listening for the next input…")
                continue

    except KeyboardInterrupt:
        print("\n👋 Stopped by user.")

if __name__ == "__main__":
    # Optional: set volume on boot
    # os.system("amixer sset 'Master' 75% unmute")
    main()
